### ISSUE TITLE
Do I need a RAST/PATRIC login if I want to view ModelSEED models when running on a local machine?

### ISSUE THREAD

**Issue by krcurtis** [ModelSEED/ModelSEED-UI#102]
I'm new to ModelSEED models, and I'd like to view some ModelSEED models on my local machine, in part because the web service http://seed-viewer.theseed.org/ is down (which I think would also let me view models).  I also tried a SEED plugin for Cytoscape, but that didn't seem to work either. I can run a server locally with the "http-server -o" command from the github repository, but it seems to require me to have a RAST account.  I've applied for one, but that seems to be a manual process, and I'm not sure when that will happen, or if my local copy of ModelSEED-UI will be able to talk to it correctly when/if I get one.

Thanks in advance!

**Comment by samseaver** [comment]
@krcurtis,

First of all, yes, you can use http-server, but we recommend nginx, we like to use it for our local testing. Regardless, the data for ModelSEED is stored in PATRIC workspaces that is only accessible via use of a RAST or PATRIC account, so even if you were to run the website locally, you still need an account to log in and see your models.

Thanks
Sam

**Comment by krcurtis** [comment]
Okay, that helps, I'm going to look at the ModelSEED command line tools, and libSBML for viewing the downloaded models instead. Thanks.

**Comment by samseaver** [comment]
@krcurtis What approach are you taking for the command line tools? The most direct way of exploring the ModelSEED data is to use the PATRIC CLI:
https://docs.patricbrc.org/cli_tutorial/cli_installation.html
You can use your RAST account with p3-login and ws-ls / ws-get to find / download the data you want.

**Comment by krcurtis** [comment]
I've started with some already downloaded model files, so currently, I've tried the python libsbml library, and that seems to be working okay so far.  Though, it was very helpful to see the more fancy website UI to get an idea of what to expect in the files.

**Comment by samseaver** [comment]
OK, if it's working for you, I'm glad to hear it.
