### ISSUE TITLE
Number of reactions and compounds is inconsistent

### ISSUE THREAD

**Issue by mmundy42** [ModelSEED/ModelSEED-UI#12]
The number of reactions and compounds is inconsistent between the summary of the model page (see screenshot) and the tabs in the model viewer.  I think the values on the summary page are the ones that are incorrect (reaction and compound numbers are reversed).

![screen shot 2015-06-15 at 4 56 25 pm](https://cloud.githubusercontent.com/assets/2896238/8215413/43210f6e-14f5-11e5-8d96-eb026d92c836.png)

**Comment by mmundy42** [comment]
Oops, that was the wrong screenshot.  Here's the correct one.
![screen shot 2015-06-17 at 1 35 37 pm](https://cloud.githubusercontent.com/assets/2896238/8215505/e63e5e54-14f5-11e5-9e36-19cfba3038cd.png)

**Comment by nconrad** [comment]
Nice catch, thanks.
