### ISSUE TITLE
add compounds to medium: search does not work

### ISSUE THREAD

**Issue by jotech** [ModelSEED/ModelSEED-UI#122]
I try to add new compounds to a user defined medium but the search to select compounds isn't working anymore.
 (User Data -> My Media -> My_Media -> Edit -> Add compounds)
I can enter text but nothing is found, even for compounds which were listed previously, e.g. H2O

This has been working in February 2019 and seems to be related to v2.5?!

**Comment by samseaver** [comment]
Dear @jotech I apologize for the late response, thank you for highlighting this issue, and I'm pleased to tell you that we found the problem. Unfortunately, we've had some turnover of hardware in our testing environment, which has delayed me in re-deploying the bug fix, I hope to get that done this week.

**Comment by jotech** [comment]
@samseaver thanks for your efforts :)

**Comment by samseaver** [comment]
@jotech We deployed the bugfix today, let us know if you have any further problems.
Thanks
Sam

**Comment by jotech** [comment]
alright it's working again, thank you a lot!
