### ISSUE TITLE
Reaction details are not displayed, hangs in "loading"

### ISSUE THREAD

**Issue by mmundy42** [ModelSEED/ModelSEED-UI#13]
In the model viewer, if you click on the link for a reaction in the Reactions tab, a new tab for the reaction is added but it hangs in "loading".  Maybe the lookup needs to remove the compartment suffix?

![screen shot 2015-06-15 at 4 56 25 pm](https://cloud.githubusercontent.com/assets/2896238/8215413/43210f6e-14f5-11e5-8d96-eb026d92c836.png)

**Comment by nconrad** [comment]
nah, I need to rewrite that code to use SOLR where needed for the data below.  The tabs will also look like the rest of the site (and are responsive).  Should have that later today.

![screen shot 2015-06-17 at 2 02 45 pm](https://cloud.githubusercontent.com/assets/1194246/8216173/73adaa70-14fa-11e5-909f-0129ab30a3b7.png)
