### ISSUE TITLE
fix genome searches with spaces

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ModelSEED-UI#2]

**Comment by mmundy42** [comment]
Confirmed that a genome search with a space does not hang.  But the result includes items that don't match the filter.  In the attached screenshot, a Bacteroides finegoldii is included in the results for a search for Bacteroides thetaiota
![screen shot 2015-06-17 at 2 04 46 pm](https://cloud.githubusercontent.com/assets/2896238/8216532/cb1158e6-14fc-11e5-90b9-3e872f5964c6.png)

**Comment by chian** [comment]
I don't see a screenshot

**Comment by nconrad** [comment]
@chian, you may need to view screenshots at the github issue page?

**Comment by mmundy42** [comment]
Looks like you need to follow the link and view the issue on Github to see the attached images.
