### ISSUE TITLE
Back button from media page goes to reaction list instead of media list

### ISSUE THREAD

**Issue by mmundy42** [ModelSEED/ModelSEED-UI#23]
On the Biochemistry tab, if I go to the "Public Media" section and click on a media, a page is displayed that shows the compounds in the media.  When I click the back button in the browser, the "Reactions" section is displayed instead of the "Public Media" section.  That's frustrating if you searched for media and have to repeat the search after looking at the media that you found.

**Comment by nconrad** [comment]
Sure... it would also be nice to not have to maintain caches of data in my application... but I'm not really sure our system is designed to support *any kind* of functionality found in web application after year 2000.

**Comment by nconrad** [comment]
*grunts*

**Comment by nconrad** [comment]
This should be fixed in most cases.  There's a little more work to be done around tabs in general, but new tickets could be opened.
