### ISSUE TITLE
Additional IDs for biochemistry 

### ISSUE THREAD

**Issue by jplfaria** [ModelSEED/ModelSEED-UI#29]
I was showing the new website to a couple of people at COBRA and by looking at the biochemistry page I was asked if we had KEGG IDs and E.C. numbers as those were available in old ModelSEED. 

@cshenry are we planning to add these back?

**Comment by nconrad** [comment]
Yes, we need to add this.  I technically could do this now, but was hoping this issue would be resolved: https://github.com/ModelSEED/ModelSEEDDatabase/issues/12

**Comment by janakagithub** [comment]
Reiterating on Jose's point, many users (including us) who look at our Biochemistry data would want to see mapping EC, SEED functional roles, KEGG, MetaCyc ids. Old modelSEED site users expect minimally to see same Biochemistry information in the new site.

**Comment by jplfaria** [comment]
It's also important to show some of  that information/IDs in the model reactions tab. 
We don't want users to go back and forward between the My Models and Biochemistry tab, to check that information/IDs for the reactions on their model(s). 

We should discuss this better regarding what we want to display, but as Janaka said, having the same info as the old ModelSEED would be a great start.

**Comment by amikaili** [comment]
New MODELSEED-UI production code has been released, and tagged 'v2.0', in the 'master' branch. GitHub is no longer used for bug tracking, though. Please send an email to help@modelseed.org, with the subject MODELSEED-43. The email server will post the email as a comment to the MODELSEED-43 ticket, in Jira.

**Comment by samseaver** [comment]
This is now resolved
