### ISSUE TITLE
Beta/MVP effort

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ModelSEED-UI#44]
- [x] 1) remove all advanced options in reconstruct/fba/gapfill (for now)
- [ ] 2) enhance my models page with status\* [stalled]
- [x] 3) enhance notifications with completion status
- [ ] 4) fix the comparison page :(
- [x] 5) remove fba/gapfill counts (for now)
- [x] 6) add 'forgot password?' link to RAST/PATRIC
- [x] 7) add help text on how to annotate gnomes via RAST/PATRIC
- [ ] 8) spruce up 'my models' as time allows
- [x] 9) point model view gene links to RAST
- [x] 10) move user to 'my media' after copying media
- [x] 11) log out of other tabs/windows on logout.

'*' involves significant time over other items.
Commit messages will follow below.  Deployed items are checked above.

**Comment by cshenry** [comment]
need to fix the gene links in the model view for models of RAST genomes. Currently, these point to PATRIC, but we need them to point to RAST.

**Comment by nconrad** [comment]
Thanks.  Added.

**Comment by nconrad** [comment]
I deployed the three above.  I was working on #2, but i thought it was pretty confusing because workspace folder mod times and/or list_models doesn't report the latest modification time.

**Comment by cshenry** [comment]
Neal, for (2), I think I should add status to the metadata for the model... rather than you trying to tease it out.

I would work on the other items for now. I'll try and get this done ASAP.

**Comment by samseaver** [comment]
Closing this list pending further review
