### ISSUE TITLE
New media gets saved with wrong type.

### ISSUE THREAD

**Issue by nconrad** [ModelSEED/ModelSEED-UI#48]
User tried to run reconstruction with custom media (built from UI) and gapfilling failed with:

Use of uninitialized value $Item in concatenation (.) or string at /disks/p3c/deployment/lib/Bio/KBase/ObjectAPI/utilities.pm line 332.
Type retrieved (string) does not match specified type (media)! at /disks/p3c/deployment/lib/Bio/KBase/ObjectAPI/utilities.pm line 183.
Bio::KBase::ObjectAPI::utilities::error("Type retrieved (string) does not match specified type (media)!") called at /disks/p3c/deployment/lib/Bio/ModelSEED/ProbModelSEED/ProbModelSEEDHelper.pm line 196
Bio::ModelSEED::ProbModelSEED::ProbModelSEEDHelper::error(Bio::ModelSEED::ProbModelSEED::ProbModelSEEDHelper=HASH(0x3335140), "Type retrieved (string) does not match specified type (media)!") called at /disks/p3c/deployment/lib/Bio/ModelSEED/ProbModelSEED/ProbModelSEEDHelper.pm line 41
...

**Comment by nconrad** [comment]
Also, need appropriate checkboxes on save.

**Comment by samseaver** [comment]
We've been successful in using custom media without apparent errors so will close for now
