### ISSUE TITLE
Custom media compositions for peptides

### ISSUE THREAD

**Issue by anna0101** [ModelSEED/ModelSEED-UI#49]
Hi,

I am trying to create new media compositions that include dipeptides and tripeptides but can't find any of these compounds within Model Seed to add to the media. 

Would you be able to help us with this please? Is there a way to add new dipeptides and tripeptides compounds with the corresponding ID, Formula, deltaG, detalGerr and charge for each peptide?

Many thanks

Anna

**Comment by chian** [comment]
Hi Anna,

I will let someone else who knows better provide the details, but the biochemistry file is available in the github repository. You should be able to and feel free to take out a branch and add any missing metabolites and reactions you need for your model. After that we should be able to merge the changes if all went well with the changes.

Or if you are running independently, you should be able to launch ModelSeed with your biochemistry file.

Hope that helps!

Best,
Nick

**Comment by anna0101** [comment]
Hi Nick,


Thanks for your email.


Would you be able to send me the biochemistry file please? I can't seem to find it in the repository.


Many thanks


Anna



________________________________

**Comment by jplfaria** [comment]
Hi Anna,

This is our biochemistry repo: https://github.com/ModelSEED/ModelSEEDDatabase/tree/master/Biochemistry

You can checkout the repo add your cpds and then submit a pull request.

**Comment by anna0101** [comment]
Hi Nick,


I previously had annotated genomes imported from RAST into the "genome" and "mine" folder within Model Seed but these have suddenly disappeared. I can still see the annotated genomes in RAST and in the "all my files" folder but i can't see them in the "mine" genomes folder.


Please advise,


Many thanks.


Anna


________________________________

**Comment by chian** [comment]
Anna,

This is going to have to be a @chrishenry question.

Best,
Nick

**Comment by anna0101** [comment]
Hi Nick,

Sorry to keep emailing you. Do you have the email address for @chrishenry?

Many thanks

Anna

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by chian** [comment]
Anna,

Not a problem. The communications are great. I like seeing the broader involvement we've gotten recently!

I've cc'd Chris Henry. Feel free to email again if you don't get a reply. 

Best,
Nick

**Comment by chrishenry** [comment]
Hi @chian. As I am the wrong Chris Henry, I don't think I'll be able to help with your annotated genome files.

However, I would recommend minifying and concat'ing your JS, as it looks like you have quite a large payload.

Best of luck!

**Comment by nconrad** [comment]
Hi @anna0101, the rast-annotated genomes list issue (under "mine") was fixed earlier today.  There was a power outage causing the server to go down for some time.  

@chrishenry, I am minifying and concat'ing JS with https://github.com/ModelSEED/ModelSEED-UI#build for the time being.  Sorry for mixup.

**Comment by anna0101** [comment]
Hello,


I am trying to add new compounds (dipeptides and tripeptides) to the model seed database so I can perform metabolic reconstructions. Do I just need to modify the compounds.master.tsv file or do I also need to modify the compartments.master.tsv and  reactions.master.tsv files as well? I ask as I cant seem to find any  information on dipeptides and tripeptides with regards to reaction pathways (rxns) and compartment data.


Many thanks


Anna



________________________________

**Comment by chian** [comment]
Anna,

You'll have to modify all of those to get the right reactions in the right places. Otherwise the compounds will have no attachment to any other reaction/compounds in the model.

Best,
Nick

**Comment by anna0101** [comment]
Thanks Nick,


I'll start modifying the files. I've tried adding some new media to the "my media" folder but it doesn't seem to be working. I'm guessing the server isn't working well right now?


Anna




________________________________

**Comment by mmundy42** [comment]
Anna,

Here are some more details for you. You'll need to add new compounds and reactions in https://github.com/ModelSEED/ModelSEEDDatabase. The first step is update the master biochemistry files. Look in https://github.com/ModelSEED/ModelSEEDDatabase/blob/master/Biochemistry/README.md for information on the format of the files. The reaction and compound IDs need to be unique.

The second step is to update the templates that are used for reconstructing models of your organisms. Look in https://github.com/ModelSEED/ModelSEEDDatabase/blob/master/Templates/README.md for information on the format of the files and directions for building a template.

If the README files don't make sense, post an issue in the ModelSEEDDatabase repo and I can try to clarify.

**Comment by anna0101** [comment]
Thanks Mike,


I am trying to perform reconstructions with custom modified media but it keeps failing. I have substituted glucose with succinate. Attached is an example of a file I am working with. Please advise


Thanks


Anna



________________________________

**Comment by mmundy42** [comment]
Anna, I don't see a file attached. If it is small, can you paste the contents in a comment?

**Comment by anna0101** [comment]
id name concentration minflux maxflux
cpd00001 H2O 0.001 -100 100
cpd00007 O2 0.001 -100 100
cpd00011 CO2 0.001 -100 0
cpd00013 NH3 0.001 -100 5
cpd00030 Mn2+ 0.001 -100 100
cpd00034 Zn2+ 0.001 -100 100
cpd00036 Succinate 0.001 -100 100
cpd00048 Sulfate 0.001 -100 5
cpd00058 Cu2+ 0.001 -100 100
cpd00063 Ca2+ 0.001 -100 100
cpd00067 H+ 0.001 -100 100
cpd00099 Cl- 0.001 -100 100
cpd00149 Co2+ 0.001 -100 100
cpd00205 K+ 0.001 -100 100
cpd00254 Mg 0.001 -100 100
cpd00971 Na+ 0.001 -100 100
cpd01665 D-O-Phosphoserine 0.001 -100 5
cpd10515 Fe2+ 0.001 -100 100
cpd10516 fe3 0.001 -100 100


I've substituted Succinate with Glucose in the Phosphate-O-Phospho-D-Serine media. Hope that helps.




________________________________

**Comment by samseaver** [comment]
@anna0101 I'm closing without comment. We've made significant changes to the website, so if you encounter any new problems, do let us know.
