### ISSUE TITLE
API hard coded limit reached

### ISSUE THREAD

**Issue by smoretti** [ModelSEED/ModelSEED-UI#52]
Hi
I try to get ModelSEED compounds with the API.
There are 27,693 compounds unfortunately whatever limit value I use in the query, I can only get 25,000 compounds.
Looks to have a hard coded limit somewhere.

**Comment by nconrad** [comment]
Hello, 

Yeah, the only way to get the other 2,693 compounds is to use the `&limit(start_position, num_of_rows)` param, i.e, `&limit(3000,25000)`. 

However, if you are just looking to download the biochem, all the data is available/curated here https://github.com/ModelSEED/ModelSEEDDatabase   You can create tickets for any issues in the data there as well.

**Comment by smoretti** [comment]
It works for me but it looks to be `&limit(num_of_rows,start_position)` and not `&limit(start_position, num_of_rows)`
Anyway thanks
