### ISSUE TITLE
Unicode strings in few compound and reaction names

### ISSUE THREAD

**Issue by smoretti** [ModelSEED/ModelSEED-UI#53]
Hi
There are some weird Unicode strings in few compound and reaction names.
E.g.
- compound cpd15811 in name and aliases
- reaction rxn10486 in name(, equation) and aliases
- reaction rxn12184 in abbreviation and aliases

I can provide a full list of you want

**Comment by JamesJeffryes** [comment]
This issue was moved to ModelSEED/ModelSEEDDatabase#46
