### ISSUE TITLE
Some reactions don't have reactants and/or products

### ISSUE THREAD

**Issue by smoretti** [ModelSEED/ModelSEED-UI#55]
Hi

Some reactions don't have reactants and products.
E.g.
- rxn14154
- rxn00000
- rxn14393

Some reactions don't have reactants or products.
E.g.
- rxn13783

**Comment by samseaver** [comment]
Hi Sebastien, I'm responsible for maintaining the master list of reactions and compounds at ModelSEEDDatabase, but I haven't been updating the databases that are reached using the ModelSEED API.

But to compound things, there are probably several ways in which you can do so, can you let me know which repository you are using for the API, and which URLs you are using to instantiate the service?

Thanks
Sam

**Comment by smoretti** [comment]
I use https://www.patricbrc.org/api/model_compound and https://www.patricbrc.org/api/model_reaction
The same URLs used on the ModelSeed.org web site

**Comment by JamesJeffryes** [comment]
This issue was moved to ModelSEED/ModelSEEDDatabase#42
