### ISSUE TITLE
Malformed EC strings in JSON

### ISSUE THREAD

**Issue by smoretti** [ModelSEED/ModelSEED-UI#56]
Hi

There are lots of badly formatted EC numbers in the JSON returned by the API.
Some have spaces in front of the EC number; some have several EC number per entry in the EC JSON array, separated by 
- *\* or **
- *\* / *\* 
- several white spaces

some EC strings end with 
- **,**
- **)** characters

**Comment by JamesJeffryes** [comment]
This issue was moved to ModelSEED/ModelSEEDDatabase#50
