### ISSUE TITLE
Compound with unexpected characters in formula

### ISSUE THREAD

**Issue by smoretti** [ModelSEED/ModelSEED-UI#58]
Hi

I found some compounds with unexpected characters in formula
E.g.
- AsH-1O3.H4O2.O.Sb2  what is **-**?
- H2O6P2*2 is `*` for polymer with n=2 ???
- C11H14NO9R4* what is `*` there?

**Comment by smoretti** [comment]
Also for cpd19876 with **C33H60I2O10n** Is *n* for the whole formula?

**Comment by JamesJeffryes** [comment]
This issue was moved to ModelSEED/ModelSEEDDatabase#43
