### ISSUE TITLE
Malformed InChI

### ISSUE THREAD

**Issue by smoretti** [ModelSEED/ModelSEED-UI#60]
We found about 1208 InChI strings that cannot be read by the software Chemaxon from the ModelSEED compound data.
E.g.
- cpd00194 InChI=1S/C12H14N2.Cl2H2/c1-13-7-3-11(4-8-13)12-5-9-14(2)10-6-12;;/h3-10H,1-2H3;2*1H/q+2;;
- cpd00271    InChI=1S/C6N6.Fe/c6*1-2;/q;;;;;;-3
- cpd00418    InChI=1S/NO/c1-2/rad

**Comment by smoretti** [comment]
Also
*cpd00766 InChI=1S/C6H7O6/c7-1-2(8)5-3(9)4(10)6(11)12-5/h2,5,7-8,10H,1H2/t2-,5+/m0/s1/rad

**Comment by JamesJeffryes** [comment]
This issue was moved to ModelSEED/ModelSEEDDatabase#41
