### ISSUE TITLE
Problem accessing new model - Authentication error

### ISSUE THREAD

**Issue by diriano** [ModelSEED/ModelSEED-UI#61]
Dear Sirs,

I have created a new model (1520.77), out of a genome annotated with RAST. But once I tried to access the model, I always get an Authentication error, something like (Using Chrome 51.0.2704.103 (Official Build) (64-bit)):

{"data":{"status":401,"data":null,"error":["User Unauthorized"]},"status":401,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"headers":{"Authorization":"OAuth un=diriano|tokenid=15FE0454-BAE6-11E6-B96C-F516692E0674|expiry=1512476805|client_id=diriano|token_type=Bearer|SigningSubject=http://rast.nmpdr.org/goauth/keys/E087E220-F8B1-11E3-9175-BD9D42A49C03|this_is_globus=globus_style_token|sig=148ed7d7cb29102f38a25026aa3ba11bd3db5fe2c58d33f75a6e802b3b0e8b88a2e62614fac3f888643213eb2a5a9f41ea743026afa915a89509654b1f2692924c145c265163ba15b6da12fc449406959c4b903e89a789f8aab04bbcad4e087ad0b32a353262e95d32e713112a8191da5e6b13f2911b258d3e5c48d6bec5ae57","Accept":"application/json, text/plain, */*"},"url":"https://p3.theseed.org/services/shock_api/node/4315b3a7-eb51-46c2-92cc-a1662690a590?download&compression=gzip"},"statusText":"Unauthorized"}

this is happening to all of my models, most of them created a while back. I cannot access them anymore.

I will appreciate it very much if you can help me in getting access to my models again.

Thanks you very much in advance,

Best,
Diego Riano

**Comment by samseaver** [comment]
@diriano I apologize that no-one ever got back to you, though we've made significant changes to the website, do you still have these problems? Due to the time of the issue, I'm closing it without further comment, but please re-open or create a new issue if you'd like.
