### ISSUE TITLE
Untrimmed names/aliases and duplicated aliases

### ISSUE THREAD

**Issue by smoretti** [ModelSEED/ModelSEED-UI#62]
Some reactions have untrimmed (space characters in front or at the end of string) names and aliases.

E.g. rxn13772 or rxn12186

This produces duplicated aliases (e.g. rxn12186) one name: with the name prefixed with a blank character, and one name: with the right name without blank prefix.

**Comment by JamesJeffryes** [comment]
This issue was moved to ModelSEED/ModelSEEDDatabase#40
